pdb_path=r"home/workspace/Master/MegSite/data/PDB/"
tsv_path=r"home/workspace/Master/MegSite/data/tsv/"
result_path=r"home/workspace/Master/MegSite/result/"
model_path=r"home/workspace/Master/MegSite/model/"
HHblits=r"home/workspace/Master/software/hhsuite/bin/hhblits"
HHBLITS_DB=r"home/workspace/Master/database/uniclust30_2018_08/uniclust30_2018_08"